### ISSUE TITLE
MiningDrunkBot stuck at pub

### ISSUE THREAD

**Issue by ghost** [Protoalliance/vindinium-client#16]
I tried running MiningDrunkBot in training mode but I notice the bot gets stuck at the pub. It doesn't look like it timed out, so there must be an issue with the bot's logic.

Here is the app.log file for MiningDrunkBot. It includes a complete run and a partial second run: https://gist.github.com/WumpaFruit/ecb935d4ee636e26de2f

**Comment by meneal** [comment]
I know where it's broken I think   I'll take a look.

**Comment by meneal** [comment]
So this actually ended up being a really crazy bug.  If you look in the ProtoGameState you'll notice that there is this block that adds in adjacent vertices.  But Bstempi had actually left the pubs out of that because they could not be traversed.  Well my first stab at fixing my issues with not having adjacent vertices for pubs was to just add adjacent vertices to the graph for the pub vertices.  Well, the problem with that is that the bot actually tries to traverse those squares!!!

So I have come up with an alternate solution.  Instead of adding the vertices to the regular graph, I added them to the actual pub object.  This is much better for multiple reasons, but a side effect is that it also fixes the bug.  Anyway, closing.
